### ISSUE TITLE
not prestashop 8.0 compatible

### ISSUE THREAD

**Issue by itsolon** [jtl-software/connector-prestashop#14]
im sure you know it but i do not know where else to ask:
will jtl prestashop connector be able to connect to prestashop 8 some time in future?

**Comment by eveneme** [comment]
+1 Please update

**Comment by rueckert-digital** [comment]
+1 Please update

**Comment by bbbenjie** [comment]
I am also urgently waiting for an update that is compatible with the latest PrestaShop Version 8.
The PrestaShop 1.7.8 versions are only compatible up to PHP 7.4. PHP 7.4 has reached its EOL and will therefore not see security updates anymore since the end of November 2022, so a PrestaShop update is strongly recommended for security reasons.

JTL should therefore react here for the benefit of its customers.

**Comment by Platzke-jtl** [comment]
version 1.13.3 should now be compartible with presta 8

**Comment by Rus-Design** [comment]
> version 1.13.3 should now be compartible with presta 8

hi. where is version 1.13.3?
